"""remove date column from info_grouping_requests

Revision ID: 37d4ed2b712b
Revises: dc06f47c1884
Create Date: 2026-04-22 08:59:40.416098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d4ed2b712b'
down_revision = 'dc06f47c1884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info_grouping_requests', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info_grouping_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
