"""create grouping_requests table

Revision ID: dc06f47c1884
Revises: e133fde6737c
Create Date: 2026-04-22 08:09:06.550220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc06f47c1884'
down_revision = 'e133fde6737c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grouping_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_request', sa.Integer(), nullable=False),
    sa.Column('id_info_grouping_request', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_info_grouping_request'], ['info_grouping_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_request'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grouping_requests')
    # ### end Alembic commands ###
